module RemoteTaskManager
{
	struct Metrics
	{
		float cpuUsage;
		float memoryUsage;
		float memoryTotal;
		float diskUsage;
		float diskTotal;
	};

	struct ServerInfo
	{
		string name;
		string OS;
		long cpuAmount;
		float memoryTotal;
		float diskTotal;
	};

	interface MetricsServer
	{
		Metrics GetMetrics();
		boolean GetHeartbeat();
		ServerInfo GetServerInfo();
		string GetServerId();
	};
};