/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{
	public interface IMetricsServerOperations
	{
		[IdlName("GetMetrics")]
		public RemoteTaskManager.Metrics GetMetrics();
		[IdlName("GetHeartbeat")]
		public bool GetHeartbeat();
		[IdlName("GetServerInfo")]
		public RemoteTaskManager.ServerInfo GetServerInfo();
		[IdlName("GetServerId")]
		[return: WideChar(false)]
		public string GetServerId();
	}
}

