/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{
	public interface IMetricsServerOperations
	{
		[IdlName("getCurrentCpuUsage")]
		public float getCurrentCpuUsage();
		[IdlName("getAvailableRAM")]
		public float getAvailableRAM();
		[IdlName("getTotalDisk")]
		public float getTotalDisk();
	}
}

