/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{
	[IdlName("MetricsServer")]
	[RepositoryID("IDL:RemoteTaskManager/MetricsServer:1.0")]
	[Helper(typeof(MetricsServerHelper))]
	[Stub(typeof(_MetricsServerStub))]
	public interface IMetricsServer : CORBA.IIDLEntity, CORBA.IObject, IMetricsServerOperations
	{
	}
}

