/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{

	public abstract class MetricsServerPOA: PortableServer.Servant, CORBA.IInvokeHandler, IMetricsServerOperations
	{
		static private Dictionary<string,int> _opsDict = new Dictionary<string,int>();
		static MetricsServerPOA()
		{
			_opsDict.Add("getCurrentCpuUsage", 0);
			_opsDict.Add("getAvailableRAM", 1);
			_opsDict.Add("getTotalDisk", 2);
		}
		private string[] _ids = {"IDL:RemoteTaskManager/MetricsServer:1.0"};

		[IdlName("getCurrentCpuUsage")]
		public abstract float getCurrentCpuUsage();
		[IdlName("getAvailableRAM")]
		public abstract float getAvailableRAM();
		[IdlName("getTotalDisk")]
		public abstract float getTotalDisk();

		public override string[] _AllInterfaces(PortableServer.IPOA poa, byte[] objId)
		{
			return _ids;
		}

		public virtual RemoteTaskManager.IMetricsServer _This()
		{
			return RemoteTaskManager.MetricsServerHelper.Narrow(_ThisObject());
		}

		public virtual RemoteTaskManager.IMetricsServer _This(CORBA.ORB orb)
		{
			return RemoteTaskManager.MetricsServerHelper.Narrow(_ThisObject(orb));
		}

		public CORBA.IOutputStream _Invoke(string method, CORBA.IInputStream inputStream, CORBA.IResponseHandler handler)
		{
			CORBA.IOutputStream outputStream = null;
			int opIndex;
			if (_opsDict.TryGetValue(method, out opIndex))
			{
				switch (opIndex)
				{
					case 0:
					{
							outputStream = handler.CreateReply();
							var _result = getCurrentCpuUsage();
							outputStream.WriteFloat(_result);
					}
					break;
					case 1:
					{
							outputStream = handler.CreateReply();
							var _result = getAvailableRAM();
							outputStream.WriteFloat(_result);
					}
					break;
					case 2:
					{
							outputStream = handler.CreateReply();
							var _result = getTotalDisk();
							outputStream.WriteFloat(_result);
					}
					break;
				}
				return outputStream;
			}
			else
			{
				throw new CORBA.BadOperation(method + " not found");
			}
		}
	}
}
