/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{
		public static class MetricsServerHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(MetricsServerHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:RemoteTaskManager/MetricsServer:1.0", "MetricsServer");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, RemoteTaskManager.IMetricsServer ifz)
			{
				any.InsertObject(ifz);
			}

			public static RemoteTaskManager.IMetricsServer Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:RemoteTaskManager/MetricsServer:1.0";
			}

			public static RemoteTaskManager.IMetricsServer Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_MetricsServerStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, RemoteTaskManager.IMetricsServer ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static RemoteTaskManager.IMetricsServer Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is RemoteTaskManager.IMetricsServer)
				{
					return (RemoteTaskManager.IMetricsServer)obj;
				}
				else if (obj._IsA("IDL:RemoteTaskManager/MetricsServer:1.0"))
				{
					_MetricsServerStub stub = new _MetricsServerStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static RemoteTaskManager.IMetricsServer UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is RemoteTaskManager.IMetricsServer)
				{
					return (RemoteTaskManager.IMetricsServer)obj;
				}
				else
				{
					_MetricsServerStub stub = new _MetricsServerStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
