/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{

	public abstract class MetricsServerPOA: PortableServer.Servant, CORBA.IInvokeHandler, IMetricsServerOperations
	{
		static private Dictionary<string,int> _opsDict = new Dictionary<string,int>();
		static MetricsServerPOA()
		{
			_opsDict.Add("GetMetrics", 0);
			_opsDict.Add("GetHeartbeat", 1);
			_opsDict.Add("GetServerInfo", 2);
			_opsDict.Add("GetServerId", 3);
		}
		private string[] _ids = {"IDL:RemoteTaskManager/MetricsServer:1.0"};

		[IdlName("GetMetrics")]
		public abstract RemoteTaskManager.Metrics GetMetrics();
		[IdlName("GetHeartbeat")]
		public abstract bool GetHeartbeat();
		[IdlName("GetServerInfo")]
		public abstract RemoteTaskManager.ServerInfo GetServerInfo();
		[IdlName("GetServerId")]
		[return: WideChar(false)]
		public abstract string GetServerId();

		public override string[] _AllInterfaces(PortableServer.IPOA poa, byte[] objId)
		{
			return _ids;
		}

		public virtual RemoteTaskManager.IMetricsServer _This()
		{
			return RemoteTaskManager.MetricsServerHelper.Narrow(_ThisObject());
		}

		public virtual RemoteTaskManager.IMetricsServer _This(CORBA.ORB orb)
		{
			return RemoteTaskManager.MetricsServerHelper.Narrow(_ThisObject(orb));
		}

		public CORBA.IOutputStream _Invoke(string method, CORBA.IInputStream inputStream, CORBA.IResponseHandler handler)
		{
			CORBA.IOutputStream outputStream = null;
			int opIndex;
			if (_opsDict.TryGetValue(method, out opIndex))
			{
				switch (opIndex)
				{
					case 0:
					{
							outputStream = handler.CreateReply();
							var _result = GetMetrics();
							RemoteTaskManager.MetricsHelper.Write(outputStream, _result);
					}
					break;
					case 1:
					{
							outputStream = handler.CreateReply();
							var _result = GetHeartbeat();
							outputStream.WriteBoolean(_result);
					}
					break;
					case 2:
					{
							outputStream = handler.CreateReply();
							var _result = GetServerInfo();
							RemoteTaskManager.ServerInfoHelper.Write(outputStream, _result);
					}
					break;
					case 3:
					{
							outputStream = handler.CreateReply();
							var _result = GetServerId();
							outputStream.WriteString(_result);
					}
					break;
				}
				return outputStream;
			}
			else
			{
				throw new CORBA.BadOperation(method + " not found");
			}
		}
	}
}
