/**
 * Generated by DotNetORb.IdlCompiler
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RemoteTaskManager
{

	public class MetricsServerPOATie: MetricsServerPOA
	{
		public IMetricsServerOperations _OperationsDelegate { get; set; }
		private PortableServer.IPOA _poa;

		public MetricsServerPOATie(IMetricsServerOperations d)
		{
			_OperationsDelegate = d;
		}

		public MetricsServerPOATie(IMetricsServerOperations d, PortableServer.POA poa)
		{
			_OperationsDelegate = d;
			_poa = poa;
		}

		public override PortableServer.IPOA _DefaultPOA()
		{
			if (_poa != null)
			{
				return _poa;
			}
			return base._DefaultPOA();
		}

		public override RemoteTaskManager.IMetricsServer _This()
		{
			return RemoteTaskManager.MetricsServerHelper.Narrow(_ThisObject());
		}

		public override RemoteTaskManager.IMetricsServer _This(CORBA.ORB orb)
		{
			return RemoteTaskManager.MetricsServerHelper.Narrow(_ThisObject(orb));
		}

		[IdlName("GetMetrics")]
		public override RemoteTaskManager.Metrics GetMetrics()
		{
			return _OperationsDelegate.GetMetrics();
		}
		[IdlName("GetHeartbeat")]
		public override bool GetHeartbeat()
		{
			return _OperationsDelegate.GetHeartbeat();
		}
		[IdlName("GetServerInfo")]
		public override RemoteTaskManager.ServerInfo GetServerInfo()
		{
			return _OperationsDelegate.GetServerInfo();
		}
		[IdlName("GetServerId")]
		[return: WideChar(false)]
		public override string GetServerId()
		{
			return _OperationsDelegate.GetServerId();
		}
	}
}
